# Generated by Django 5.0.3 on 2024-03-30 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_master',
            fields=[
                ('master_id', models.AutoField(primary_key=True, serialize=False)),
                ('master_name', models.CharField(max_length=25)),
                ('master_contact', models.IntegerField()),
                ('master_email', models.EmailField(max_length=254)),
                ('master_photo', models.FileField(null=True, upload_to='Files/')),
                ('master_password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('user_contact', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=25)),
                ('user_gender', models.CharField(max_length=25)),
                ('user_photo', models.FileField(null=True, upload_to='Files/')),
                ('user_proof', models.FileField(null=True, upload_to='Files/')),
                ('user_password', models.CharField(max_length=25)),
                ('user_status', models.CharField(default=0, max_length=25)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
