# Generated by Django 5.0.3 on 2024-03-30 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.CharField(max_length=100)),
                ('test_start_time', models.CharField(max_length=100)),
                ('test_end_time', models.CharField(max_length=100)),
                ('test_score', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_test_question',
            fields=[
                ('test_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_question_answer', models.CharField(max_length=100)),
                ('test_question_score', models.CharField(max_length=100)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_test')),
            ],
        ),
    ]
