# Generated by Django 5.0.1 on 2024-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_test_test_status_alter_tbl_test_test_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_test',
            name='test_start_time',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
