# Generated by Django 5.0.1 on 2024-04-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_tbl_test_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_test',
            name='test_start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
