# Generated by Django 5.0.1 on 2024-04-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('User', '0004_alter_tbl_test_test_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_test_question',
            name='question_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Master.tbl_question'),
            preserve_default=False,
        ),
    ]
